/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CurrentRouteImport } from './routes/current'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BranchesIndexRouteImport } from './routes/branches.index'
import { Route as BranchesNameRouteImport } from './routes/branches.$name'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentRoute = CurrentRouteImport.update({
  id: '/current',
  path: '/current',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesIndexRoute = BranchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BranchesRoute,
} as any)
const BranchesNameRoute = BranchesNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => BranchesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRouteWithChildren
  '/current': typeof CurrentRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/branches/$name': typeof BranchesNameRoute
  '/branches/': typeof BranchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/current': typeof CurrentRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/branches/$name': typeof BranchesNameRoute
  '/branches': typeof BranchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branches': typeof BranchesRouteWithChildren
  '/current': typeof CurrentRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/branches/$name': typeof BranchesNameRoute
  '/branches/': typeof BranchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/branches'
    | '/current'
    | '/login'
    | '/register'
    | '/branches/$name'
    | '/branches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/current'
    | '/login'
    | '/register'
    | '/branches/$name'
    | '/branches'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/branches'
    | '/current'
    | '/login'
    | '/register'
    | '/branches/$name'
    | '/branches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BranchesRoute: typeof BranchesRouteWithChildren
  CurrentRoute: typeof CurrentRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current': {
      id: '/current'
      path: '/current'
      fullPath: '/current'
      preLoaderRoute: typeof CurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/': {
      id: '/branches/'
      path: '/'
      fullPath: '/branches/'
      preLoaderRoute: typeof BranchesIndexRouteImport
      parentRoute: typeof BranchesRoute
    }
    '/branches/$name': {
      id: '/branches/$name'
      path: '/$name'
      fullPath: '/branches/$name'
      preLoaderRoute: typeof BranchesNameRouteImport
      parentRoute: typeof BranchesRoute
    }
  }
}

interface BranchesRouteChildren {
  BranchesNameRoute: typeof BranchesNameRoute
  BranchesIndexRoute: typeof BranchesIndexRoute
}

const BranchesRouteChildren: BranchesRouteChildren = {
  BranchesNameRoute: BranchesNameRoute,
  BranchesIndexRoute: BranchesIndexRoute,
}

const BranchesRouteWithChildren = BranchesRoute._addFileChildren(
  BranchesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BranchesRoute: BranchesRouteWithChildren,
  CurrentRoute: CurrentRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
